// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClinicaOdontologica.API.Migrations
{
    [DbContext(typeof(ClinicaOdontologicaAPIContext))]
    partial class ClinicaOdontologicaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Citas", b =>
                {
                    b.Property<int>("IdCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCita"));

                    b.Property<string>("EstadoCita")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_cita");

                    b.Property<DateTime>("FechaCita")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cita");

                    b.Property<int>("IdConsultorio")
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    b.Property<int>("IdOdontologo")
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("Motivo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("motivo");

                    b.HasKey("IdCita");

                    b.HasIndex("IdConsultorio");

                    b.HasIndex("IdOdontologo");

                    b.HasIndex("IdPaciente");

                    b.ToTable("citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Consultorios", b =>
                {
                    b.Property<int>("IdConsultorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_consultorio");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdConsultorio"));

                    b.Property<string>("Equipamiento_Principal")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("equipamiento_principal");

                    b.Property<string>("Numero_Sala")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("numero_sala");

                    b.Property<int>("Piso")
                        .HasColumnType("integer")
                        .HasColumnName("piso");

                    b.HasKey("IdConsultorio");

                    b.ToTable("consultorios");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetallesCita", b =>
                {
                    b.Property<int>("IdDetalleCita")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_detalle_cita");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDetalleCita"));

                    b.Property<decimal>("CostoAplicado")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_aplicado");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<int>("IdTratamiento")
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("observaciones");

                    b.HasKey("IdDetalleCita");

                    b.HasIndex("IdCita");

                    b.HasIndex("IdTratamiento");

                    b.ToTable("detallescita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Especialidades", b =>
                {
                    b.Property<int>("Id_Especialidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Especialidad"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_especialidad");

                    b.HasKey("Id_Especialidad");

                    b.ToTable("especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Facturas", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_factura");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("EstadoPago")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_pago");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<decimal>("Impuestos")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("impuestos");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("total");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdCita")
                        .IsUnique();

                    b.ToTable("facturas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialesMedicos", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_historial");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHistorial"));

                    b.Property<string>("Alergias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alergias");

                    b.Property<string>("EnfermedadesPrevias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("enfermedades_previas");

                    b.Property<int>("IdPaciente")
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    b.Property<string>("TipoSangre")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("tipo_sangre");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdPaciente")
                        .IsUnique();

                    b.ToTable("historialesmedicos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologos", b =>
                {
                    b.Property<int>("IdOdontologo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_odontologo");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdOdontologo"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<int?>("IdEspecialidad")
                        .IsRequired()
                        .HasColumnType("integer")
                        .HasColumnName("id_especialidad");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("RegistroMedico")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("registro_medico");

                    b.HasKey("IdOdontologo");

                    b.HasIndex("IdEspecialidad");

                    b.ToTable("odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Pacientes", b =>
                {
                    b.Property<int>("IdPaciente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_paciente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPaciente"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("apellidos");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("dni");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombres");

                    b.Property<string>("Telefono")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("telefono");

                    b.HasKey("IdPaciente");

                    b.ToTable("pacientes");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Recetas", b =>
                {
                    b.Property<int>("IdReceta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_receta");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdReceta"));

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdCita")
                        .HasColumnType("integer")
                        .HasColumnName("id_cita");

                    b.Property<string>("Indicaciones")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("indicaciones");

                    b.HasKey("IdReceta");

                    b.HasIndex("IdCita");

                    b.ToTable("recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Tratamientos", b =>
                {
                    b.Property<int>("IdTratamiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_tratamiento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdTratamiento"));

                    b.Property<decimal>("CostoBase")
                        .HasColumnType("numeric(10, 2)")
                        .HasColumnName("costo_base");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_estimada_minutos");

                    b.Property<string>("NombreTratamiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombre_tratamiento");

                    b.HasKey("IdTratamiento");

                    b.ToTable("tratamientos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Citas", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Consultorios", "Consultorio")
                        .WithMany()
                        .HasForeignKey("IdConsultorio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Odontologos", "Odontologo")
                        .WithMany("Citas")
                        .HasForeignKey("IdOdontologo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Pacientes", "Paciente")
                        .WithMany("Citas")
                        .HasForeignKey("IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Odontologo");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.DetallesCita", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Citas", "Cita")
                        .WithMany("DetallesCitas")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicaOdontologica.Modelos.Tratamientos", "Tratamiento")
                        .WithMany()
                        .HasForeignKey("IdTratamiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");

                    b.Navigation("Tratamiento");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Facturas", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Citas", "Cita")
                        .WithOne("Factura")
                        .HasForeignKey("ClinicaOdontologica.Modelos.Facturas", "IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.HistorialesMedicos", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Pacientes", "Paciente")
                        .WithOne("HistorialMedico")
                        .HasForeignKey("ClinicaOdontologica.Modelos.HistorialesMedicos", "IdPaciente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologos", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Especialidades", "Especialidades")
                        .WithMany("Odontologos")
                        .HasForeignKey("IdEspecialidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidades");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Recetas", b =>
                {
                    b.HasOne("ClinicaOdontologica.Modelos.Citas", "Cita")
                        .WithMany("Recetas")
                        .HasForeignKey("IdCita")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cita");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Citas", b =>
                {
                    b.Navigation("DetallesCitas");

                    b.Navigation("Factura");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Especialidades", b =>
                {
                    b.Navigation("Odontologos");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Odontologos", b =>
                {
                    b.Navigation("Citas");
                });

            modelBuilder.Entity("ClinicaOdontologica.Modelos.Pacientes", b =>
                {
                    b.Navigation("Citas");

                    b.Navigation("HistorialMedico");
                });
#pragma warning restore 612, 618
        }
    }
}
